version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies...
      - "[ -d backend ] && cd backend || echo 'Already in backend or root?'"
      - pip install -r requirements.txt
      - pip install pytest
  
  pre_build:
    commands:
      - echo Running tests...
      - "[ -d backend ] && cd backend || echo 'Already in backend or root?'"
      - python -m pytest tests/
  
  build:
    commands:
      - echo Building Docker image...
      - "[ -d backend ] && cd backend || echo 'Already in backend or root?'"
      - docker build -t safetasks-backend .

artifacts:
  files:
    - '**/*'
  base-directory: backend
