"""add_cascade_deletes

Revision ID: 2fd4aeb07101
Revises: 371384f52193
Create Date: 2026-02-01 20:28:43.343707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fd4aeb07101'
down_revision: Union[str, None] = '371384f52193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('call_sheets_project_id_fkey', 'call_sheets', type_='foreignkey')
    op.create_foreign_key(None, 'call_sheets', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('characters_project_id_fkey', 'characters', type_='foreignkey')
    op.create_foreign_key(None, 'characters', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('invoice_items_invoice_id_fkey', 'invoice_items', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_items', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('invoices_project_id_fkey', 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('project_budget_lines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_budget_lines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_project_budget_lines_category', table_name='project_budget_lines')
    op.drop_index('ix_project_budget_lines_organization_id', table_name='project_budget_lines')
    op.drop_index('ix_project_budget_lines_project_id', table_name='project_budget_lines')
    op.drop_constraint('project_budget_lines_project_id_fkey', 'project_budget_lines', type_='foreignkey')
    op.create_foreign_key(None, 'project_budget_lines', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('scene_characters_character_id_fkey', 'scene_characters', type_='foreignkey')
    op.drop_constraint('scene_characters_scene_id_fkey', 'scene_characters', type_='foreignkey')
    op.create_foreign_key(None, 'scene_characters', 'scenes', ['scene_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'scene_characters', 'characters', ['character_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('scenes_project_id_fkey', 'scenes', type_='foreignkey')
    op.create_foreign_key(None, 'scenes', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('service_equipment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_service_equipment_kit_id', table_name='service_equipment')
    op.drop_index('ix_service_equipment_organization_id', table_name='service_equipment')
    op.drop_index('ix_service_equipment_service_id', table_name='service_equipment')
    op.alter_column('shooting_days', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_constraint('shooting_days_project_id_fkey', 'shooting_days', type_='foreignkey')
    op.create_foreign_key(None, 'shooting_days', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_stakeholders_project_status', table_name='stakeholders')
    op.drop_index('ix_stakeholders_status', table_name='stakeholders')
    op.drop_index('ix_transactions_budget_line_id', table_name='transactions')
    op.drop_constraint('fk_transactions_invoice_id', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_project_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_project_id_fkey', 'transactions', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('fk_transactions_invoice_id', 'transactions', 'invoices', ['invoice_id'], ['id'])
    op.create_index('ix_transactions_budget_line_id', 'transactions', ['budget_line_id'], unique=False)
    op.create_index('ix_stakeholders_status', 'stakeholders', ['status'], unique=False)
    op.create_index('ix_stakeholders_project_status', 'stakeholders', ['project_id', 'status'], unique=False)
    op.drop_constraint(None, 'shooting_days', type_='foreignkey')
    op.create_foreign_key('shooting_days_project_id_fkey', 'shooting_days', 'projects', ['project_id'], ['id'])
    op.alter_column('shooting_days', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.create_index('ix_service_equipment_service_id', 'service_equipment', ['service_id'], unique=False)
    op.create_index('ix_service_equipment_organization_id', 'service_equipment', ['organization_id'], unique=False)
    op.create_index('ix_service_equipment_kit_id', 'service_equipment', ['kit_id'], unique=False)
    op.alter_column('service_equipment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.create_foreign_key('scenes_project_id_fkey', 'scenes', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'scene_characters', type_='foreignkey')
    op.drop_constraint(None, 'scene_characters', type_='foreignkey')
    op.create_foreign_key('scene_characters_scene_id_fkey', 'scene_characters', 'scenes', ['scene_id'], ['id'])
    op.create_foreign_key('scene_characters_character_id_fkey', 'scene_characters', 'characters', ['character_id'], ['id'])
    op.drop_constraint(None, 'project_budget_lines', type_='foreignkey')
    op.create_foreign_key('project_budget_lines_project_id_fkey', 'project_budget_lines', 'projects', ['project_id'], ['id'])
    op.create_index('ix_project_budget_lines_project_id', 'project_budget_lines', ['project_id'], unique=False)
    op.create_index('ix_project_budget_lines_organization_id', 'project_budget_lines', ['organization_id'], unique=False)
    op.create_index('ix_project_budget_lines_category', 'project_budget_lines', ['category'], unique=False)
    op.alter_column('project_budget_lines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_budget_lines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_project_id_fkey', 'invoices', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.create_foreign_key('invoice_items_invoice_id_fkey', 'invoice_items', 'invoices', ['invoice_id'], ['id'])
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.create_foreign_key('characters_project_id_fkey', 'characters', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'call_sheets', type_='foreignkey')
    op.create_foreign_key('call_sheets_project_id_fkey', 'call_sheets', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
