"""add_dates_to_proposals

Revision ID: 371384f52193
Revises: 52a1b2c3d4e7
Create Date: 2026-02-01 19:59:55.868279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '371384f52193'
down_revision: Union[str, None] = '52a1b2c3d4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('start_date', sa.DATE(), nullable=True))
    op.add_column('proposals', sa.Column('end_date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'end_date')
    op.drop_column('proposals', 'start_date')
    # ### end Alembic commands ###
