"""add_ai_features_tables

Revision ID: 3776f2d1424c
Revises: 2d9d5766dec7
Create Date: 2026-01-28 07:18:00.978148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3776f2d1424c'
down_revision: Union[str, None] = '2d9d5766dec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_implemented', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high')"),
    sa.CheckConstraint("recommendation_type IN ('call_sheet', 'budget', 'schedule', 'equipment')"),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('suggestion_type', sa.String(), nullable=False),
    sa.Column('suggestion_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('related_scenes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_savings_cents', sa.BIGINT(), nullable=True),
    sa.Column('estimated_time_saved_minutes', sa.Integer(), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high')"),
    sa.CheckConstraint("suggestion_type IN ('budget', 'schedule', 'casting', 'logistics', 'equipment', 'other')"),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('cost_cents', sa.BIGINT(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("request_type IN ('script_analysis', 'budget_estimation', 'call_sheet_suggestion', 'text_analysis', 'other')"),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('script_text', sa.Text(), nullable=False),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('cost_cents', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("analysis_type IN ('full', 'characters', 'scenes', 'locations')"),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('script_analyses')
    op.drop_table('ai_usage_logs')
    op.drop_table('ai_suggestions')
    op.drop_table('ai_recommendations')
    # ### end Alembic commands ###
