"""upgrade_billing_events_ledger

Revision ID: 5a6f1774fcda
Revises: e4d1c0370bf6
Create Date: 2026-02-10 23:10:26.164700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a6f1774fcda'
down_revision: Union[str, None] = 'e4d1c0370bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_events', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('billing_events', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('billing_events', sa.Column('provider', sa.String(), nullable=False, server_default='stripe'))
    op.add_column('billing_events', sa.Column('amount_cents', sa.BIGINT(), nullable=True))
    op.add_column('billing_events', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('billing_events', sa.Column('plan_name', sa.String(), nullable=True))
    op.add_column('billing_events', sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('billing_events', 'stripe_event_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_billing_events_stripe_event_id', 'billing_events', type_='unique')
    op.create_foreign_key(None, 'billing_events', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'billing_events', type_='foreignkey')
    op.create_unique_constraint('uq_billing_events_stripe_event_id', 'billing_events', ['stripe_event_id'])
    op.alter_column('billing_events', 'stripe_event_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('billing_events', 'event_metadata')
    op.drop_column('billing_events', 'plan_name')
    op.drop_column('billing_events', 'currency')
    op.drop_column('billing_events', 'amount_cents')
    op.drop_column('billing_events', 'provider')
    op.drop_column('billing_events', 'organization_id')
    op.drop_column('billing_events', 'external_id')
    # ### end Alembic commands ###
