"""refactor_stakeholder_supplier

Revision ID: 75bc2a9f80e1
Revises: 4e8f9a2b5c3d
Create Date: 2026-01-29 14:15:26.229067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75bc2a9f80e1'
down_revision: Union[str, None] = '4e8f9a2b5c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Custom data migration: Create suppliers for existing stakeholders
    connection = op.get_bind()
    import uuid
    
    # 1. Select all stakeholders where supplier_id IS NULL
    stakeholders = connection.execute(sa.text("SELECT id, organization_id, name, email, phone FROM stakeholders WHERE supplier_id IS NULL")).fetchall()
    
    if stakeholders:
        print(f"Migrating {len(stakeholders)} stakeholders without supplier link...")
        
        for sh in stakeholders:
            new_supplier_id = uuid.uuid4()
            
            # 2. Create new Supplier for each
            connection.execute(sa.text(
                """
                INSERT INTO suppliers (id, organization_id, name, category, email, phone, is_active, created_at, updated_at)
                VALUES (:id, :org_id, :name, 'freelancer', :email, :phone, true, now(), now())
                """
            ), {
                "id": new_supplier_id, 
                "org_id": sh.organization_id, 
                "name": sh.name, 
                "email": sh.email, 
                "phone": sh.phone
            })
            
            # 3. Link Stakeholder to new Supplier
            connection.execute(sa.text(
                "UPDATE stakeholders SET supplier_id = :supplier_id WHERE id = :id"
            ), {"supplier_id": new_supplier_id, "id": sh.id})

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stakeholders', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('stakeholders', 'name')
    op.drop_column('stakeholders', 'email')
    op.drop_column('stakeholders', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stakeholders', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stakeholders', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stakeholders', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('stakeholders', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
