"""Add stakeholder_id to transactions

Revision ID: 990dd3078435
Revises: 9ef25dd07157
Create Date: 2026-01-29 23:56:53.613574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990dd3078435'
down_revision: Union[str, None] = '9ef25dd07157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('stakeholder_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'stakeholders', ['stakeholder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'stakeholder_id')
    # ### end Alembic commands ###
