"""add_refund_tables

Revision ID: 9b759fba7ef2
Revises: 984bca99f12b
Create Date: 2026-02-12 18:06:30.198234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b759fba7ef2'
down_revision: Union[str, None] = '984bca99f12b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. billing_purchases
    op.create_table('billing_purchases',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('source_billing_event_id', sa.UUID(), nullable=True),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('external_charge_id', sa.String(), nullable=True),
        sa.Column('plan_name', sa.String(), nullable=True),
        sa.Column('amount_paid_cents', sa.BigInteger(), nullable=False),
        sa.Column('currency', sa.String(), server_default='BRL', nullable=False),
        sa.Column('paid_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('total_refunded_cents', sa.BigInteger(), server_default='0', nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.ForeignKeyConstraint(['source_billing_event_id'], ['billing_events.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_purchases_organization_id'), 'billing_purchases', ['organization_id'], unique=False)

    # 2. refund_requests
    op.create_table('refund_requests',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('purchase_id', sa.UUID(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('requester_profile_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.String(), server_default='requested', nullable=False),
        sa.Column('reason_code', sa.String(), nullable=True),
        sa.Column('reason_detail', sa.String(), nullable=True),
        sa.Column('amount_paid_cents', sa.BigInteger(), nullable=False),
        sa.Column('consumed_usage_value_cents', sa.BigInteger(), server_default='0', nullable=False),
        sa.Column('calculated_max_refund_cents', sa.BigInteger(), nullable=False),
        sa.Column('approved_amount_cents', sa.BigInteger(), nullable=True),
        sa.Column('eligible_until', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('requested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('decided_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('processed_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.ForeignKeyConstraint(['purchase_id'], ['billing_purchases.id'], ),
        sa.ForeignKeyConstraint(['requester_profile_id'], ['profiles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refund_requests_organization_id'), 'refund_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_refund_requests_status'), 'refund_requests', ['status'], unique=False)

    # 3. refund_transactions
    op.create_table('refund_transactions',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('refund_request_id', sa.UUID(), nullable=False),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('provider_refund_id', sa.String(), nullable=True),
        sa.Column('amount_cents', sa.BigInteger(), nullable=False),
        sa.Column('status', sa.String(), server_default='pending', nullable=False),
        sa.Column('failure_reason', sa.String(), nullable=True),
        sa.Column('requested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['refund_request_id'], ['refund_requests.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 4. refund_events
    op.create_table('refund_events',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('refund_request_id', sa.UUID(), nullable=False),
        sa.Column('actor_type', sa.String(), nullable=False),
        sa.Column('actor_id', sa.UUID(), nullable=True),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('event_metadata', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['refund_request_id'], ['refund_requests.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 5. platform_admin_users
    op.create_table('platform_admin_users',
        sa.Column('profile_id', sa.UUID(), nullable=False),
        sa.Column('role', sa.String(), server_default='superadmin', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
        sa.PrimaryKeyConstraint('profile_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_admin_users')
    op.drop_table('refund_events')
    op.drop_table('refund_transactions')
    op.drop_index(op.f('ix_refund_requests_status'), table_name='refund_requests')
    op.drop_index(op.f('ix_refund_requests_organization_id'), table_name='refund_requests')
    op.drop_table('refund_requests')
    op.drop_index(op.f('ix_billing_purchases_organization_id'), table_name='billing_purchases')
    op.drop_table('billing_purchases')
    # ### end Alembic commands ###
