"""restore_all_tables_final

Revision ID: a2daed2c3b65
Revises: bb22cc33dd44
Create Date: 2026-02-10 22:34:58.630676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2daed2c3b65'
down_revision: Union[str, None] = 'bb22cc33dd44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # This migration was auto-generated to restore tables but they already exist in production.
    # Marking as pass to skip re-creation and allow alembic head to sync.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_logs')
    op.drop_table('transactions')
    op.drop_table('scene_characters')
    op.drop_table('invoice_items')
    op.drop_table('shooting_day_crew')
    op.drop_table('scenes')
    op.drop_table('proposal_services')
    op.drop_table('project_budget_lines')
    op.drop_table('invoices')
    op.drop_table('stakeholders')
    op.drop_table('shooting_days')
    op.drop_table('script_analyses')
    op.drop_table('proposals')
    op.drop_table('project_services')
    op.drop_table('project_drive_folders')
    op.drop_table('project_assignments')
    op.drop_table('kit_item_usage_logs')
    op.drop_table('cloud_file_references')
    op.drop_table('characters')
    op.drop_table('ai_usage_logs')
    op.drop_table('ai_suggestions')
    op.drop_table('ai_recommendations')
    op.drop_table('service_equipment')
    op.drop_table('projects')
    op.drop_index('uq_org_invites_pending', table_name='organization_invites', postgresql_where="status = 'pending'")
    op.drop_table('organization_invites')
    op.drop_table('kit_items')
    op.drop_table('tax_tables')
    op.drop_table('suppliers')
    op.drop_table('stored_files')
    op.drop_table('services')
    op.drop_table('organization_usage')
    op.drop_table('notifications')
    op.drop_table('kits')
    op.drop_table('google_drive_credentials')
    op.drop_table('entitlements')
    op.drop_table('clients')
    op.drop_table('profiles')
    op.drop_table('plans')
    op.drop_table('organizations')
    op.drop_table('billing_events')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
