"""add_payment_status_to_transactions

Revision ID: beb962120563
Revises: 2fd4aeb07101
Create Date: 2026-02-01 22:32:35.920181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb962120563'
down_revision: Union[str, None] = '2fd4aeb07101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_status', sa.String(), nullable=False, server_default='pending'))
    op.add_column('transactions', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('approved_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'profiles', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'rejection_reason')
    op.drop_column('transactions', 'approved_at')
    op.drop_column('transactions', 'approved_by')
    op.drop_column('transactions', 'payment_status')
    # ### end Alembic commands ###
