"""add_phone_to_profiles

Revision ID: c9a002b46e8b
Revises: 9ccc21f6d2bd
Create Date: 2026-02-08 00:07:31.143572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a002b46e8b'
down_revision: Union[str, None] = '9ccc21f6d2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_org_is_active', table_name='clients')
    op.drop_index('ix_cloud_sync_status_org_sync_started_at', table_name='cloud_sync_status')
    op.drop_index('ix_cloud_sync_status_org_sync_status', table_name='cloud_sync_status')
    op.drop_index('ix_kit_item_usage_logs_kit_item_id', table_name='kit_item_usage_logs')
    op.drop_index('ix_kit_item_usage_logs_organization_id', table_name='kit_item_usage_logs')
    op.drop_index('ix_kit_item_usage_logs_project_id', table_name='kit_item_usage_logs')
    op.drop_index('ix_kit_items_org_health_status', table_name='kit_items')
    op.drop_index('ix_org_invites_org_id', table_name='organization_invites')
    op.drop_index('ix_org_invites_token_hash', table_name='organization_invites')
    op.add_column('profiles', sa.Column('phone', sa.String(), nullable=True))
    op.drop_index('ix_projects_org_budget_status_updated_at', table_name='projects')
    op.drop_index('ix_projects_org_status', table_name='projects')
    op.drop_index('ix_transactions_org_category_type_payment_status', table_name='transactions')
    op.drop_index('ix_transactions_org_payment_status_dates', table_name='transactions')
    op.drop_index('ix_transactions_org_transaction_date', table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transactions_org_transaction_date', 'transactions', ['organization_id', 'transaction_date'], unique=False)
    op.create_index('ix_transactions_org_payment_status_dates', 'transactions', ['organization_id', 'payment_status', 'transaction_date', 'created_at'], unique=False)
    op.create_index('ix_transactions_org_category_type_payment_status', 'transactions', ['organization_id', 'category', 'type', 'payment_status'], unique=False)
    op.create_index('ix_projects_org_status', 'projects', ['organization_id', 'status'], unique=False)
    op.create_index('ix_projects_org_budget_status_updated_at', 'projects', ['organization_id', 'budget_status', 'updated_at'], unique=False)
    op.drop_column('profiles', 'phone')
    op.create_index('ix_org_invites_token_hash', 'organization_invites', ['token_hash'], unique=False)
    op.create_index('ix_org_invites_org_id', 'organization_invites', ['org_id'], unique=False)
    op.create_index('ix_kit_items_org_health_status', 'kit_items', ['organization_id', 'health_status'], unique=False)
    op.create_index('ix_kit_item_usage_logs_project_id', 'kit_item_usage_logs', ['project_id'], unique=False)
    op.create_index('ix_kit_item_usage_logs_organization_id', 'kit_item_usage_logs', ['organization_id'], unique=False)
    op.create_index('ix_kit_item_usage_logs_kit_item_id', 'kit_item_usage_logs', ['kit_item_id'], unique=False)
    op.create_index('ix_cloud_sync_status_org_sync_status', 'cloud_sync_status', ['organization_id', 'sync_status'], unique=False)
    op.create_index('ix_cloud_sync_status_org_sync_started_at', 'cloud_sync_status', ['organization_id', 'sync_started_at'], unique=False)
    op.create_index('ix_clients_org_is_active', 'clients', ['organization_id', 'is_active'], unique=False)
    # ### end Alembic commands ###
