"""add_tax_id_to_organizations

Revision ID: cfd0e492ab96
Revises: 75bc2a9f80e1
Create Date: 2026-01-29 19:34:20.222431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd0e492ab96'
down_revision: Union[str, None] = '75bc2a9f80e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('tax_id', sa.String(), nullable=True))
    op.add_column('stakeholders', sa.Column('name', sa.String(), server_default='Unknown', nullable=False))
    op.add_column('stakeholders', sa.Column('email', sa.String(), nullable=True))
    op.add_column('stakeholders', sa.Column('phone', sa.String(), nullable=True))
    op.alter_column('stakeholders', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stakeholders', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('stakeholders', 'phone')
    op.drop_column('stakeholders', 'email')
    op.drop_column('stakeholders', 'name')
    op.drop_column('organizations', 'tax_id')
    # ### end Alembic commands ###
