"""initial_schema_week_5

Revision ID: d83d8750c988
Revises: 
Create Date: 2026-01-25 14:22:00.913574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83d8750c988'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoice_items_invoice_id_fkey', 'invoice_items', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_items', 'invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.create_foreign_key('invoice_items_invoice_id_fkey', 'invoice_items', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
