"""restore_circular_fks

Revision ID: e4d1c0370bf6
Revises: a2daed2c3b65
Create Date: 2026-02-10 22:36:40.184784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4d1c0370bf6'
down_revision: Union[str, None] = 'a2daed2c3b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_bank_accounts_organization', 'bank_accounts', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('fk_organizations_billing_contact', 'organizations', 'profiles', ['billing_contact_user_id'], ['id'])
    op.create_foreign_key('fk_organizations_default_bank', 'organizations', 'bank_accounts', ['default_bank_account_id'], ['id'])
    op.create_foreign_key('fk_organizations_owner_profile', 'organizations', 'profiles', ['owner_profile_id'], ['id'])
    op.create_foreign_key('fk_organizations_plan', 'organizations', 'plans', ['plan_id'], ['id'])
    op.create_foreign_key('fk_profiles_organization', 'profiles', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_profiles_organization', 'profiles', type_='foreignkey')
    op.drop_constraint('fk_organizations_plan', 'organizations', type_='foreignkey')
    op.drop_constraint('fk_organizations_owner_profile', 'organizations', type_='foreignkey')
    op.drop_constraint('fk_organizations_default_bank', 'organizations', type_='foreignkey')
    op.drop_constraint('fk_organizations_billing_contact', 'organizations', type_='foreignkey')
    op.drop_constraint('fk_bank_accounts_organization', 'bank_accounts', type_='foreignkey')
    # ### end Alembic commands ###
